//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace quanlysachmoi.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class BookTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BookTable()
        {
            this.BookFineTables = new HashSet<BookFineTable>();
            this.BookReturnTables = new HashSet<BookReturnTable>();
            this.IssueBookTables = new HashSet<IssueBookTable>();
            this.PurchaseDetailTables = new HashSet<PurchaseDetailTable>();
        }
    
        public int BookID { get; set; }
        public int UserID { get; set; }
        [Required(ErrorMessage = "Please select department")]

        public int DepartmentID { get; set; }
        [Required(ErrorMessage = "Please enter book type")]
        public int BookTypeID { get; set; }
        [Required(ErrorMessage = "Please enter book title")]
        public string BookTitle { get; set; }
        [Required(ErrorMessage = "Please enter short description")]
        public string ShortDescription { get; set; }
        [Required(ErrorMessage = "Please enter author name")]
        public string Author { get; set; }
        [Required(ErrorMessage = "Please enter book name")]
        public string BookName { get; set; }
        [Required(ErrorMessage = "Please enter book edition")]
        public double Edition { get; set; }
        [Required(ErrorMessage = "Please enter total copies")]
        public int TotalCopies { get; set; }
        public System.DateTime RegDate { get; set; }
        [Required(ErrorMessage = "Please enter book price")]
        [DataType(DataType.Currency)]
        public double Price { get; set; }
        public string Description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookFineTable> BookFineTables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookReturnTable> BookReturnTables { get; set; }
        public virtual BookTypeTable BookTypeTable { get; set; }
        public virtual DepartmentTable DepartmentTable { get; set; }
        public virtual UserTable UserTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IssueBookTable> IssueBookTables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseDetailTable> PurchaseDetailTables { get; set; }
    }
}
